In [ ]:
1+5

6

In [ ]:
6/3

2.0

In [ ]:
print(8*2)

16


In [ ]:
print("hello world")

hello world


In [ ]:
earnings = 3
price = 12
pre_ratio = price / earnings
print(pre_ratio)

4.0


In [ ]:
print(earnings)

3


In [ ]:
1==1

True

In [ ]:
months = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec']

In [ ]:
months[1]

'Feb'

In [ ]:
months[-1]

'Dec'

In [ ]:
months

['Jan',
 'Feb',
 'Mar',
 'Apr',
 'May',
 'Jun',
 'Jul',
 'Aug',
 'Sep',
 'Oct',
 'Nov',
 'Dec']

In [ ]:
# print JUne

months[5]

'Jun'

In [ ]:
months[2:5]

['Mar', 'Apr', 'May']

In [ ]:
import numpy as np

In [ ]:
A=[10,5,2,1,4,12]

In [ ]:
np.median(A)

np.float64(4.5)

In [ ]:
np.mean(A)

np.float64(5.666666666666667)

In [ ]:
# Try to Create array using NumPy for list
a = [37,40,20,50,32]
b = [98,53,30,85,69]

In [ ]:
print(a+b)

[37, 40, 20, 50, 32, 98, 53, 30, 85, 69]


In [ ]:
a_arr= np.array(a)
b_arr= np.array(b)

In [ ]:
print(a_arr+b_arr)

[135  93  50 135 101]


In [ ]:
print(a_arr)
print(a_arr + 10)

[37 40 20 50 32]
[47 50 30 60 42]


In [ ]:
# Example : ABC Company has reported monthly revenue and cost as below:
revenue = [123, 5, 33, 10, 12, 20, 40, 1.2, 9.9, 0.5, 11.11, 999]
cost = [10, 15, 100, 10, 5, 2, 13.1, 10, 99, 0, 3.2, 555]

In [ ]:
rev = np.array(revenue)
cs = np.array(cost)
profit = rev - cs
print(profit)

[113.   -10.   -67.     0.     7.    18.    26.9   -8.8  -89.1    0.5
   7.91 444.  ]


In [ ]:
# Calculate Total revenue, Total cost and Total profit of the company
# Hint : Using np.sum()
Total_revenue = np.sum(rev)
Total_cost = np.sum(cs)
Total_profit = np.sum(profit)


In [ ]:
print(Total_revenue)
print(Total_cost)
print(Total_profit)

1264.71
822.3
442.41


In [ ]:
# Calculating Average, Median and Standart Deviation of the revenue
print(np.mean(rev))
print(np.median(rev))
print(np.std(rev))

105.3925
11.555
271.32701417063134


In [ ]:
!pip install numpy_financial

In [ ]:
import numpy_financial as npf

In [ ]:
# 10-year bond 5% with YTM 3%, pls compute price of this bond

rate = 0.03
nper = 10
pmt = 50
fv = 1000
print(round(npf.pv(rate=rate,nper=nper,pmt=pmt,fv=fv),2))

-1170.6


In [ ]:
cash_flow = np.array([-250000, 100000, 150000, 200000, 250000, 300000])

In [ ]:
print(round(npf.npv(rate=rate,values=cash_flow),2))

652409.49
