<a href="https://colab.research.google.com/github/sandwith2004/Salalalandsand/blob/main/%E0%B8%A2%E0%B8%B4%E0%B8%99%E0%B8%94%E0%B8%B5%E0%B8%95%E0%B9%89%E0%B8%AD%E0%B8%99%E0%B8%A3%E0%B8%B1%E0%B8%9A%E0%B8%AA%E0%B8%B9%E0%B9%88_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("hello world")

hello world


In [3]:
earnings = 3
price = 12
pre_ratio = price / earnings
print(pre_ratio)

4.0


In [21]:
print(earnings*price)

36.0


In [22]:
print(earnings)

3


In [17]:
months[0]

'Jan'

In [19]:
months

['Jan',
 'Feb',
 'Mar',
 'Apr',
 'May',
 'Jun',
 'Jul',
 'Aug',
 'Sep',
 'Oct',
 'Nov',
 'Dec']

In [20]:
months[2:5]

['Mar', 'Apr', 'May']

In [23]:
months[0]

'Jan'

In [24]:
months[-1]

'Dec'

In [26]:
months[4]

'May'

In [27]:
months[1:5:2]

['Feb', 'Apr']

In [28]:
months[0:11:3]

['Jan', 'Apr', 'Jul', 'Oct']

In [29]:
months[2:12:3]

['Mar', 'Jun', 'Sep', 'Dec']

Numpy

In [30]:
# Import NumPy Library to the Colab

import numpy as np

In [33]:
from google.colab import files
uploaded = files.upload()  # เลือกไฟล์ auto-mpg.csv จากคอมของคุณ

Saving auto-mpg.csv to auto-mpg.csv


upload file จากเครื่องขึ้นcolap

In [37]:
import numpy as np

In [35]:
A=[10,5,2,1,4,12]

In [39]:
np.median(A)

np.float64(4.5)

In [40]:
np.mean(A)

np.float64(5.666666666666667)

In [41]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [42]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [44]:
abac = np.arange(10)

In [45]:
abac

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [54]:
np.arange(0,21,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [47]:
# Runing Number with condition
# np.arange(Start, Until-1, by how much)
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [48]:
# Try to Create array using NumPy for list
a = [37,40,20,50,32]
b = [98,53,30,85,69]

In [49]:
print(a+b)

[37, 40, 20, 50, 32, 98, 53, 30, 85, 69]


In [50]:
# Example of arrays
a_arr = np.array(a)
b_arr = np.array(b)
print(a_arr + b_arr)

[135  93  50 135 101]


In [51]:
#เอาsetบวกด้วยสิบทั้งเซ็ต
print(a_arr + 10)

[47 50 30 60 42]


In [52]:
#เอาsetคูณด้วยสองทั้งเซ็ต
print(a_arr * 2)

[ 74  80  40 100  64]


In [55]:
#เอาเซ็ตAหารด้วยสองทั้งเซ็ต
print(a_arr / 2)

[18.5 20.  10.  25.  16. ]


In [58]:
#เอาเซ็ตAยกกำลังสองทั้งเซ็ต
print(a_arr ** 2)

[1369 1600  400 2500 1024]


In [57]:
#เอาเซ็ตAคูณเซ็ตB
print(a_arr * b_arr)

[3626 2120  600 4250 2208]


In [59]:
#หาsqure root
print(np.sqrt(a_arr))

[6.08276253 6.32455532 4.47213595 7.07106781 5.65685425]


In [60]:
# Example : ABC Company has reported monthly revenue and cost as below:
revenue = [123, 5, 33, 10, 12, 20, 40, 1.2, 9.9, 0.5, 11.11, 999]
cost = [10, 15, 100, 10, 5, 2, 13.1, 10, 99, 0, 3.2, 555]

In [61]:
#หาprofit
revenue = np.array(revenue)
cost = np.array(cost)
profit = revenue - cost

In [62]:
print(profit)

[113.   -10.   -67.     0.     7.    18.    26.9   -8.8  -89.1    0.5
   7.91 444.  ]


In [63]:
#หาtotal revenue
Total_revenue = np.sum(revenue)
print(Total_revenue)

1264.71


In [64]:
#หาtotal cost
Total_cost = np.sum(cost)
print(Total_cost)

822.3


In [65]:
#หา total profit
Total_profit = np.sum(profit)
print(Total_profit)

442.41


In [66]:
#mean of total revenue
print(np.mean(revenue))

105.3925


In [67]:
#median of total revenue
print(np.median(revenue))

11.555


In [68]:
#standard deviation of total revenue
print(np.std(revenue))

271.32701417063134


In [70]:
#หา correlation coefficient
print(np.corrcoef(revenue, cost))

[[1.         0.96686431]
 [0.96686431 1.        ]]


In [77]:
revenue

array([1.230e+02, 5.000e+00, 3.300e+01, 1.000e+01, 1.200e+01, 2.000e+01,
       4.000e+01, 1.200e+00, 9.900e+00, 5.000e-01, 1.111e+01, 9.990e+02])

In [78]:
revenue[10]

np.float64(11.11)

In [79]:
# Selecting revenue from Mar, Jun, Aug, Dec
Qend_revenue = np.array([2,5,8,11])
revenue[Qend_revenue]

array([ 33. ,  20. ,   9.9, 999. ])